# Don't steal my credential oh nooooo



































# It's coming, prepare your notes






























spring:
  datasource:
    username: postgres
    password: limon1441
  oauth2:
    client:
      registration:
        google:
          client-id: "2370289415-2o86tnhs66skrn84fian70scjb2bnb9u.apps.googleusercontent.com"
          client-secret: "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"
  mail:
    username: aman.nazarkulov@gmail.com
    password: yfab gdwr mmgj atyn

jwt:
  secret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
  expiration: 86400000
  refreshExpiration: 320000